---
repos:
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.8.6
      hooks:
          - id: ruff
            args: [--fix]
          - id: ruff-format
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: debug-statements
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.16.1
      hooks:
          - id: mypy
            additional_dependencies:
                - types-requests
                - attrs
                - pytest
                - typing_extensions>=4.5
    - repo: https://github.com/tox-dev/pyproject-fmt
      rev: v2.6.0
      hooks:
          - id: pyproject-fmt

    # Backstage linter
    - repo: local
      hooks:
          - id: backstage-entity-validator
            name: backstage-entity-validator
            language: system
            files: catalog-info\.yaml$
            entry: npx @roadiehq/backstage-entity-validator validate-entity
            exclude: |
                (?x)^(
                  user_repo.*
                )$
