language: python
cache: pip
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
install:
- pip install -U pytest setuptools_scm
- pip install -e .
script: py.test
deploy:
  provider: pypi
  user: ronny
  password:
    secure: duJF5zUxuOllVoNDs4SePxVtWsiiLiXIfHx6zIl9K0pc5trr8wKAMD003apSUzoaiRGveSC0pVuofnZN6L0c2iK/hcHuk2Eenur2zB/k5c0VlAy35kOyVjdQXkWgGLqp1lZ8+E9UjS9HP3XHzzbFJ38lP+fS6ENkAZtn1msgztcAk1as46d6+KVFjaJruQZ/E0U9U+F/eGAY2HiVRNyI1kxZ1JGbJ6hYNAZTYrfm/eaEyfPGHvEYmRzAnWiMjW0eBxL5QNG9q5CZr+T1XW6EG12w8ZQrxN64h4cMhDA2m65TIiKTNXwORHYtVLUIl90Mw0NT0iE4fYrxkSoPvgETx54T5UpN1yAmJUK0lQ8wuyxnSqXPjctuHNeoP6THv8wgsDnmQHdwrJkQ7b7sEt0IhfqvFFl/921aObujg6VQjvXXV89vYCi2zZp7LadR3y/Q4kXqsDavYblmFGCyMkvZFs9C2WcD7QZksRA99WKJT/ON6u6Icy+ZyBiaqu2PSccKnmVNzq8OaFGsXLV0ZiPd/x6zAB72KSRCOmqY1DhZxYOt3aojbFj9Wq+ZbhrI99woAJY1YI1xrYZsOzSScC9bVfP6pxAXDMUtW46o5ni9YfzxBRoNtRdrN9Zo+w4SjJb6CC7QkEKJcFhSey3A2Dwg5TzAghmTKDUq1Vijr+HOoW0=
  on:
    tags: true
    python: '2.7'
  distributions: sdist bdist_wheel
