---
name: python tests+artifacts+release

on:
    pull_request:
    push:
        branches:
            - main
        tags:
            - v*
    release:
        types: [published]


jobs:
    build-and-inspect:
        runs-on: ubuntu-latest
        name: Build & inspect package
        outputs:
            python-versions: ${{ steps.build.outputs.supported_python_classifiers_json_array }}
            package-name: ${{ steps.build.outputs.package_name }}
            package-version: ${{ steps.build.outputs.package_version }}
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - id: build
              uses: hynek/build-and-inspect-python-package@v2

    test:
        runs-on: ubuntu-latest
        needs: [build-and-inspect]
        strategy:
            matrix:
                python-version: ${{ fromJSON(needs.build-and-inspect.outputs.python-versions) }}
                install-from: [dist/*.whl]
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}
            - uses: actions/cache@v4
              with:
                  path: ~/.cache/pip
                  key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
            - name: Install dependencies
              run: pip install pytest
            - uses: actions/download-artifact@v4
              with:
                  name: Packages
                  path: dist
            - name: install ${{ matrix.install-from }}
              run: pip install ${{ matrix.install-from }}
            - name: pytest
              run: pytest



    upload-to-pypi:
        name: Upload package to PyPI
        runs-on: ubuntu-latest
        if: ${{ github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags') }}
        needs: [build-and-inspect, test]

        permissions:
            # IMPORTANT: this permission is mandatory for trusted publishing
            id-token: write
        steps:
            - name: Download built artifact to dist/
              uses: actions/download-artifact@v4
              with:
                  name: Packages
                  path: dist
            - name: Publish package to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
